### ISSUE TITLE
feat: `readable()` in additon to `save()`

### ISSUE THREAD

**Issue by shevernitskiy** [DjDeveloperr/skia_canvas#27]
Is this possible to get ReadableStream instead of saving to the file or saving to the Buffer?

**Comment by DjDeveloperr** [comment]
There isn’t any direct API to do that, but maybe we’ll be able to offload encoding to a different thread and make encode async at least. Streaming is probably not possible due to the nature of API skia exposes for encoding.

**Comment by shevernitskiy** [comment]
Thanks for the answer.

**Comment by DjDeveloperr** [comment]
It's still desirable to have async encoding so I've opened a separate issue: #28
