### ISSUE TITLE
[bug] `fillText` failed with non usual latin symbols

### ISSUE THREAD

**Issue by shevernitskiy** [DjDeveloperr/skia_canvas#30]
I trying to draw text with cyrillic chars and got error.
```ts
ctx.font = '20px "Consolas"';
ctx.fillText("Ё", 50, 50);
```
```shell
error: Uncaught (in promise) Error: failed to fill text
      throw new Error("failed to fill text");
            ^
    at CanvasRenderingContext2D.fillText (https://deno.land/x/skia_canvas@0.4.0/src/context2d.ts:296:13)
    at drawChar (file:///E:/programming/ts/charmap/src/main.ts:51:7)
    at file:///E:/programming/ts/charmap/src/main.ts:59:7
    at Array.forEach (<anonymous>)
    at file:///E:/programming/ts/charmap/src/main.ts:58:9
    at Array.forEach (<anonymous>)
    at drawMatrix (file:///E:/programming/ts/charmap/src/main.ts:57:10)
    at file:///E:/programming/ts/charmap/src/main.ts:37:1
```

I checked on other unicode symbols and seems like it only work with main EN ASCII table.
Using unicode hexcodes `\u0090` also gives error.
It there any way to solve this issue?

**Comment by DjDeveloperr** [comment]
Can you try and see if importing from https://raw.githubusercontent.com/DjDeveloperr/skia_canvas/76fe0856d743cf4bce289f3fad06259133f0d825/mod.ts fixes the issue?

**Comment by DjDeveloperr** [comment]
![image](https://user-images.githubusercontent.com/43033058/207538741-0e56ee21-62ad-4ab6-b900-c96529643606.png)

Indeed does

**Comment by shevernitskiy** [comment]
Yep, its work. Thanks for istanst fix!
