### ISSUE TITLE
Canvas creates weird pixels on border

### ISSUE THREAD

**Issue by Harusakii** [DjDeveloperr/skia_canvas#45]
So basically, when running this simple code:

```
import { createCanvas } from "https://deno.land/x/skia_canvas@0.5.0/mod.ts";

const canvas = createCanvas(300, 300);
const ctx = canvas.getContext("2d");

// Set line width
ctx.lineWidth = 10;

// Wall
ctx.strokeRect(75, 140, 150, 110);

// Door
ctx.fillRect(130, 190, 40, 60);

// Roof
ctx.beginPath();
ctx.moveTo(50, 140);
ctx.lineTo(150, 60);
ctx.lineTo(250, 140);
ctx.closePath();
ctx.stroke();

console.log(canvas.toDataURL("png", 100))
```
it should return a simple house, which it does, but the problem is that it also generates weird pixels on the border of the images:

how it should look like (canvas in nodejs);
![1](https://user-images.githubusercontent.com/96204239/213887146-d30d41a9-b4a8-4b18-bbae-338b458a24e5.png)

how it looks like with this package for deno:
![2](https://user-images.githubusercontent.com/96204239/213887172-dcac5c36-9994-44df-89c2-612ed201bb94.png)

in this example you see that the top left of the image has like different colors to single pixels which is very weird (zoom to the top left to see it better)

**Comment by Harusakii** [comment]
Sometimes it goes completely wild like this:
![3](https://user-images.githubusercontent.com/96204239/213887753-9ac47bdf-b2ed-4772-9af5-8efa157624f0.png)

**Comment by nhrones** [comment]
I'm sorry, but every one of those images on this page, look exactly the same!  I'm on an older Win10 laptop.
What is the pixel density of your display?  Is it retina?

**Comment by nhrones** [comment]
I'll wait for the experts to chime in.  I just wanted you to know that I can't see any issue on my low res laptop.

**Comment by Harusakii** [comment]
![image](https://user-images.githubusercontent.com/96204239/213889556-ee1d2df6-8885-41e0-b61c-c380f59d0b95.png)
![image](https://user-images.githubusercontent.com/96204239/213889585-959ab0cd-e0f1-4252-badc-5ea19dfb7e98.png)

here there are zoomed in on a white background, also the pics are 300x300

**Comment by nhrones** [comment]
Try this 
```js
const canvas = createCanvas(300, 300);
const ctx = canvas.getContext("2d");

// refresh the surface
ctx.clearRect(0, 0, 300, 300;

// draw the house
```

**Comment by Harusakii** [comment]
oh yeah, it indeed did help! But still very weird, I would expect a completely new and cleared Context when I create one and not need to clear it manually.

Maybe write this in the documentation ahah. thank you very much though (also for your replying speed)!
