### ISSUE TITLE
An error related to `ImageData`

### ISSUE THREAD

**Issue by BlackGlory** [DjDeveloperr/skia_canvas#65]
Code:
```ts
import { createCanvas, Image } from 'https://deno.land/x/skia_canvas@0.5.6/mod.ts'

const inputFilename = 'input.jpg'
const outputFilename = 'output.png'

const image = await Image.load(inputFilename)

const canvas = createCanvas(image.width, image.height)
const ctx = canvas.getContext('2d')

ctx.drawImage(image, 0, 0)
const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height)
ctx.putImageData(imageData, 0, 0)

canvas.save(outputFilename, 'png')
```

Input:
![input](https://github.com/DjDeveloperr/skia_canvas/assets/1365962/460916f9-3d80-494b-a547-64006ef21258)

Output:
![output](https://github.com/DjDeveloperr/skia_canvas/assets/1365962/29a3871d-bd9d-4f0e-aba2-5f45afb9e64a)

**Comment by DjDeveloperr** [comment]
https://github.com/DjDeveloperr/skia_canvas/commit/8fc4f9ac9be913ab3a6b174badb2e097f285f3c3

this was an interesting one... caused by a typo 😓 
thanks for reporting!
